#!/usr/bin/env bash

## Download phpMyadmin
cd /web/content
curl -o pma.tar.gz https://files.phpmyadmin.net/phpMyAdmin/4.9.4/phpMyAdmin-4.9.4-english.tar.gz
tar -xzf pma.tar.gz
rm -f pma.tar.gz
mv phpMyAdmin-4.9.4-english pma
cd pma
echo "<?php $cfg['blowfish_secret']='';$i=0;$i++;$cfg['Servers'][$i]['auth_type']='config';$cfg['Servers'][$i]['host']='db';$cfg['Servers'][$i]['connect_type']='tcp';$cfg['Servers'][$i]['compress']=false;$cfg['Servers'][$i]['AllowNoPassword']=false;$cfg['Servers'][$i]['host']=getenv('DB_PORT_3306_TCP_ADDR');$cfg['Servers'][$i]['verbose']='Service Center';$cfg['Servers'][$i]['user']=getenv('MYSQL_USER_NAME');$cfg['Servers'][$i]['password']=getenv('MYSQL_USER_PASS');$i++;$cfg['Servers'][$i]['auth_type']='config';$cfg['Servers'][$i]['host']='db';$cfg['Servers'][$i]['connect_type']='tcp';$cfg['Servers'][$i]['compress']=false;$cfg['Servers'][$i]['AllowNoPassword']=false;$cfg['Servers'][$i]['host']='ndconsoledb';$cfg['Servers'][$i]['verbose']='Console';$cfg['Servers'][$i]['user']=getenv('MYSQL_USER_NAME');$cfg['Servers'][$i]['password']=getenv('MYSQL_USER_PASS');$i++;$cfg['Servers'][$i]['auth_type']='config';$cfg['Servers'][$i]['host']='db';$cfg['Servers'][$i]['connect_type']='tcp';$cfg['Servers'][$i]['compress']=false;$cfg['Servers'][$i]['AllowNoPassword']=false;$cfg['Servers'][$i]['host']='ndnewvehicledatamanagerdb';$cfg['Servers'][$i]['verbose']='VDM';$cfg['Servers'][$i]['user']=getenv('MYSQL_USER_NAME');$cfg['Servers'][$i]['password']=getenv('MYSQL_USER_PASS');$i++;$cfg['Servers'][$i]['auth_type']='config';$cfg['Servers'][$i]['host']='db';$cfg['Servers'][$i]['connect_type']='tcp';$cfg['Servers'][$i]['compress']=false;$cfg['Servers'][$i]['AllowNoPassword']=false;$cfg['Servers'][$i]['host']='ndenquirymanagerv1db';$cfg['Servers'][$i]['verbose']='NEM1';$cfg['Servers'][$i]['user']=getenv('MYSQL_USER_NAME');$cfg['Servers'][$i]['password']=getenv('MYSQL_USER_PASS');$i++;$cfg['Servers'][$i]['auth_type']='config';$cfg['Servers'][$i]['host']='db';$cfg['Servers'][$i]['connect_type']='tcp';$cfg['Servers'][$i]['compress']=false;$cfg['Servers'][$i]['AllowNoPassword']=false;$cfg['Servers'][$i]['host']='ndenquirymanagerv2db';$cfg['Servers'][$i]['verbose']='NEM2';$cfg['Servers'][$i]['user']=getenv('MYSQL_USER_NAME');$cfg['Servers'][$i]['password']=getenv('MYSQL_USER_PASS');$cfg['UploadDir']='';$cfg['SaveDir']='';" > config.inc.php